add: deploy compose

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -10,16 +10,20 @@ inputs:
   api_token:
     description: 'Dokploy API token'
     required: true
+  compose_id:
+    description: 'Dokploy compose ID'
+    required: false
   application_id:
     description: 'Dokploy application ID'
-    required: true
+    required: false
   image_uri:
     description: 'Image URI'
-    required: true
+    required: false
 runs:
   using: "composite"
   steps:
     - name: Update app docker provider
+      if: ${{ inputs.application_id }} 
       shell: bash
       env:
         DOKPLOY_URL: ${{ inputs.dokploy_url }}
@@ -43,6 +47,7 @@ runs:
         fi
 
     - name: Trigger deployment
+      if: ${{ inputs.application_id }} 
       shell: bash
       env:
         DOKPLOY_URL: ${{ inputs.dokploy_url }}
@@ -59,6 +64,29 @@ runs:
           -o /dev/null \
           -s)
         
+        if [ "$response" -ne 200 ]; then
+          echo "Deployment failed with status code: $response"
+          exit 1
+        fi
+
+    - name: Trigger deployment
+      if: ${{ inputs.compose_id }} 
+      shell: bash
+      env:
+        DOKPLOY_URL: ${{ inputs.dokploy_url }}
+        DOKPLOY_API_TOKEN: ${{ inputs.api_token }}
+        DOKPLOY_COMPOSE_ID: ${{ inputs.compose_id }}
+      run: |
+        response=$(curl -X 'POST' \
+          "$DOKPLOY_URL/api/compose.deploy" \
+          -H 'Accept: application/json' \
+          -H 'Content-Type: application/json' \
+          -H "Authorization: Bearer $DOKPLOY_API_TOKEN" \
+          -d "{\"composeId\": \"$DOKPLOY_COMPOSE_ID\"}" \
+          -w "%{http_code}" \
+          -o /dev/null \
+          -s)
+
         if [ "$response" -ne 200 ]; then
           echo "Deployment failed with status code: $response"
           exit 1
